spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

rabbitmq:
    queue:
        name: queue_slnntk_demo
    exchange:
        name: exchange_slnntk_demo
    routing:
        key: routing_key_slnntk_demo